wget "https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/EfvTORckuctOqS03fo5Y5rUB5ImhajgS5ihZvjcZtwECpg?e=wXrRSB&download=1" -O CoreView_313.tar.gz
wget "https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/Ef1NRudJL3dDrUA3z9vLRf4BCOjMHBxVz9bjgOpe05X8qw?e=UDUqPk&download=1" -O CoreView_315.tar.gz
wget "https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/EcS5vjN0RKFFmzHcKPpAjqgBOBAsEk0E1NGVCtXtQHdQww?e=WhO0FE&download=1" -O CoreView_377.tar.gz
wget "https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/EX_i_CMkkDBMkPPPw5e315wBsuWuRUBNp66T50Yg9ZP9PA?e=TQt8px&download=1" -O CoreView_386.tar.gz
wget "https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/EVNpNor8T1hErNUTxgU3pzQBqafPBBTnplcP3ffnrAE01w?e=8vdSSw&download=1" -O CoreView_387.tar.gz
wget "https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/EUTc3ifVZu1GtzbrnxBzmi4B-U1WFYBV4EYV-6CN5M74wA?e=wBDE6u&download=1" -O CoreView_390.tar.gz
wget "https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/EZBQK-ATtiJFg-DmdsOqHi0BDw2Mfpaako9ZbRyszMOemg?e=Sz2QFk&download=1" -O CoreView_392.tar.gz
wget "https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/Eeo6Qghm5vxMjmRWfDWwCgwB0mwCcqFPlEb_Gbx8sBHF8g?e=hbjCGE&download=1" -O CoreView_393.tar.gz
wget "https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/EaxzbHD66pVBujke71xQBAMBdlNhbaZYsZEUOKn8JWHH2g?e=v0SNyg&download=1" -O CoreView_394.tar.gz
